site_name: Kwahalf Zone
site_url: http://blog.kwahalf.com
site_description: A blog containing interesting software and computer engineering concepts
theme:
  name: material
  custom_dir: overrides
  logo: assets/kwahalf-high-resolution-logo.png
  favicon: assets/favicon-blog.ico
  palette:
    scheme: slate
    primary: white
    accent: red
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.footer
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Payment Integrations
        - Linux Containers
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated


hooks:
  - hooks/socialmedia.py

nav:
  - Blog:
     - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/kwahalf
      name: Kwahalf on github

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/denis-juma/

    - icon: fontawesome/brands/grunt
      link: https://denisjuma.kwahalf.com

  generator: false

copyright: Copyright &copy; 2024 Denis Juma
